######################################################################
#
# File name : iprop_nvme_dev_ref_design_wrapper_compile.do
# Created on: Mon Aug 03 13:39:44 MDT 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/xil_defaultlib
vlib msim/lib_cdc_v1_0
vlib msim/proc_sys_reset_v5_0
vlib msim/lib_pkg_v1_0
vlib msim/fifo_generator_v12_0
vlib msim/lib_fifo_v1_0
vlib msim/blk_mem_gen_v8_2
vlib msim/lib_bmg_v1_0
vlib msim/axi_pcie_v2_6
vlib msim/axi_lite_ipif_v3_0
vlib msim/lib_srl_fifo_v1_0
vlib msim/axi_uartlite_v2_0
vlib msim/generic_baseblocks_v2_1
vlib msim/axi_infrastructure_v1_1
vlib msim/axi_register_slice_v2_1
vlib msim/axi_data_fifo_v2_1
vlib msim/axi_crossbar_v2_1
vlib msim/axi_intc_v4_1
vlib msim/lmb_bram_if_cntlr_v4_0
vlib msim/mdm_v3_2
vlib msim/microblaze_v9_5
vlib msim/util_ds_buf_v2_01_a
vlib msim/axi_protocol_converter_v2_1
vlib msim/axi_clock_converter_v2_1
vlib msim/axi_dwidth_converter_v2_1

vmap xil_defaultlib msim/xil_defaultlib
vmap lib_cdc_v1_0 msim/lib_cdc_v1_0
vmap proc_sys_reset_v5_0 msim/proc_sys_reset_v5_0
vmap lib_pkg_v1_0 msim/lib_pkg_v1_0
vmap fifo_generator_v12_0 msim/fifo_generator_v12_0
vmap lib_fifo_v1_0 msim/lib_fifo_v1_0
vmap blk_mem_gen_v8_2 msim/blk_mem_gen_v8_2
vmap lib_bmg_v1_0 msim/lib_bmg_v1_0
vmap axi_pcie_v2_6 msim/axi_pcie_v2_6
vmap axi_lite_ipif_v3_0 msim/axi_lite_ipif_v3_0
vmap lib_srl_fifo_v1_0 msim/lib_srl_fifo_v1_0
vmap axi_uartlite_v2_0 msim/axi_uartlite_v2_0
vmap generic_baseblocks_v2_1 msim/generic_baseblocks_v2_1
vmap axi_infrastructure_v1_1 msim/axi_infrastructure_v1_1
vmap axi_register_slice_v2_1 msim/axi_register_slice_v2_1
vmap axi_data_fifo_v2_1 msim/axi_data_fifo_v2_1
vmap axi_crossbar_v2_1 msim/axi_crossbar_v2_1
vmap axi_intc_v4_1 msim/axi_intc_v4_1
vmap lmb_bram_if_cntlr_v4_0 msim/lmb_bram_if_cntlr_v4_0
vmap mdm_v3_2 msim/mdm_v3_2
vmap microblaze_v9_5 msim/microblaze_v9_5
vmap util_ds_buf_v2_01_a msim/util_ds_buf_v2_01_a
vmap axi_protocol_converter_v2_1 msim/axi_protocol_converter_v2_1
vmap axi_clock_converter_v2_1 msim/axi_clock_converter_v2_1
vmap axi_dwidth_converter_v2_1 msim/axi_dwidth_converter_v2_1

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_bank_cntrl.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_mc.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_bank_compare.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_bank_queue.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_rank_common.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_arb_mux.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_bank_mach.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_rank_mach.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_col_mach.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_bank_state.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_arb_row_col.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_arb_select.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_bank_common.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_rank_cntrl.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/controller/mig_7series_v2_3_round_robin_arb.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v2_3_mem_intfc.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ip_top/mig_7series_v2_3_memc_ui_top_axi.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_wrlvl_off_delay.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_wrlvl.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_mc_phy_wrapper.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_samp.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ck_addr_cmd_delay.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_poc_tap_base.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_byte_lane.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_poc_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_oclkdelay_cal.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_byte_group_io.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_mc_phy.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_lim.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_poc_meta.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_data.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_edge.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_of_pre_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_init.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_poc_pd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_prbs_rdlvl.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_mux.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_cntlr.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_poc_edge_store.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_poc_cc.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_tempmon.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_wrcal.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_4lanes.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_dqs_found_cal_hr.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_prbs_gen.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_if_post_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_dqs_found_cal.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_ocd_po_cntlr.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_phy_rdlvl.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/phy/mig_7series_v2_3_ddr_calib_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v2_3_ecc_merge_enc.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v2_3_ecc_buf.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v2_3_ecc_gen.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v2_3_fi_xor.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ecc/mig_7series_v2_3_ecc_dec_fix.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v2_3_ui_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v2_3_ui_wr_data.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v2_3_ui_rd_data.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/ui/mig_7series_v2_3_ui_cmd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_command_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_wr_cmd_fsm.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_aw_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_ar_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_incr_cmd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_cmd_translator.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_addr_decode.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_cmd_arbiter.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_w_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_or.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_comparator_sel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_and.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_cmd_fsm.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_write.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_axic_register_slice.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_axi_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_r_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_read.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_a_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_b_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_latch_or.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_reg_bank.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_carry_latch_and.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_comparator.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_axi_register_slice.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_ctrl_reg.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_simple_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_wrap_cmd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_r_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_axi_mc_w_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/axi/mig_7series_v2_3_ddr_comparator_sel_static.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v2_3_tempmon.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v2_3_iodelay_ctrl.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v2_3_infrastructure.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/clocking/mig_7series_v2_3_clk_ibuf.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/iprop_nvme_dev_ref_design_mig_7series_0_0_mig_sim.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mig_7series_0_0/iprop_nvme_dev_ref_design_mig_7series_0_0/user_design/rtl/iprop_nvme_dev_ref_design_mig_7series_0_0.v" \

vcom -64 -93 -work lib_cdc_v1_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_cdc_v1_0/3c38df9f/hdl/src/vhdl/cdc_sync.vhd" \

vcom -64 -93 -work proc_sys_reset_v5_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/upcnt_n.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/sequence.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/lpf.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/proc_sys_reset.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_proc_sys_reset_1_0/sim/iprop_nvme_dev_ref_design_proc_sys_reset_1_0.vhd" \

vcom -64 -93 -work lib_pkg_v1_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_pkg_v1_0/22b9c58c/hdl/src/vhdl/lib_pkg.vhd" \

vlog -64 -incr -work fifo_generator_v12_0  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/simulation/fifo_generator_vlog_beh.v" \

vcom -64 -93 -work fifo_generator_v12_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0_rfs.vhd" \

vlog -64 -incr -work fifo_generator_v12_0  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0_rfs.v" \

vcom -64 -93 -work lib_fifo_v1_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_fifo_v1_0/259791c0/hdl/src/vhdl/async_fifo_fg.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_fifo_v1_0/259791c0/hdl/src/vhdl/sync_fifo_fg.vhd" \

vlog -64 -incr -work blk_mem_gen_v8_2  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/834889ee/simulation/blk_mem_gen_v8_2.v" \

vcom -64 -93 -work lib_bmg_v1_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_bmg_v1_0/1cb7cddc/hdl/src/vhdl/blk_mem_gen_wrapper.vhd" \

vlog -64 -incr -work axi_pcie_v2_6  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_a_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_address_decoder.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_block_bridge.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_event_handler.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_gen_sink.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_slave.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_demux.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_destraddler.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_null_gen.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_pipeline.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx_arbiter.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx_pipeline.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx_port_mux.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_lite_ipif.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_pcie_enhanced_core_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_register_slice.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axic_register_slice.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_and.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_latch_and.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_latch_or.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_or.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_command_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_comparator.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_comparator_sel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_comparator_sel_static.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_enhanced_core_top_wrap.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_gtpa1_dual_wrapper.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_gtpa1_dual_wrapper_tile.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_rx_valid_filter_7x.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_gt_top_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_wrapper.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtx_cpllpd_ovrd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_gt_wrapper_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_pipe_rate.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_pipe_drp.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_pipe_reset.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_7x.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_bram_7x.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_bram_top_7x.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_brams_7x.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_pipe_lane.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_pipe_misc.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_pipe_pipeline.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_top.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_clock_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_drp.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_eq.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_eq_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_rate.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_rate_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_reset.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_sync.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_sync_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_user.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_user_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_wrapper.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_wrapper_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_qpll_drp_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_qpll_reset.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_qpll_wrapper_ies.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_rxeq_scan.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pselect_f.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_r_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_slave_attachment.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_w_upsizer.v" \

vcom -64 -93 -work axi_pcie_v2_6  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_enhanced_pcie.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_pcie_mm_s_pkg.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_masterbridge_rd.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_masterbridge_wr.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_s_masterbridge_rd.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_s_masterbridge_wr.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_s_masterbridge_rd.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_s_masterbridge_wr.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_s_masterbridge.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/register_block.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_read_cpl_tlp.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_read_req_tlp.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_write_req_tlp.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_slave_read.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_slave_write.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_bridge.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_pcie_mm_s.vhd" \

vlog -64 -incr -work axi_pcie_v2_6  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_clock.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_qpll_wrapper.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_common.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_qpll_drp.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_cpllpd_ovrd.v" \

vcom -64 -93 -work axi_pcie_v2_6  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_pcie.vhd" \

vlog -64 -incr -work axi_pcie_v2_6  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_pcie_0_0/trigger.v" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_pcie_0_0/sim/iprop_nvme_dev_ref_design_axi_pcie_0_0.v" \

vcom -64 -93 -work axi_lite_ipif_v3_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_lite_ipif_v3_0/876b8fe4/hdl/src/vhdl/ipif_pkg.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_lite_ipif_v3_0/876b8fe4/hdl/src/vhdl/pselect_f.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_lite_ipif_v3_0/876b8fe4/hdl/src/vhdl/address_decoder.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_lite_ipif_v3_0/876b8fe4/hdl/src/vhdl/slave_attachment.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_lite_ipif_v3_0/876b8fe4/hdl/src/vhdl/axi_lite_ipif.vhd" \

vcom -64 -93 -work lib_srl_fifo_v1_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_srl_fifo_v1_0/c6efbe92/hdl/src/vhdl/cntr_incr_decr_addn_f.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_srl_fifo_v1_0/c6efbe92/hdl/src/vhdl/dynshreg_f.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_srl_fifo_v1_0/c6efbe92/hdl/src/vhdl/srl_fifo_rbu_f.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lib_srl_fifo_v1_0/c6efbe92/hdl/src/vhdl/srl_fifo_f.vhd" \

vcom -64 -93 -work axi_uartlite_v2_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_uartlite_v2_0/c01b5c67/hdl/src/vhdl/dynshreg_i_f.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_uartlite_v2_0/c01b5c67/hdl/src/vhdl/uartlite_tx.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_uartlite_v2_0/c01b5c67/hdl/src/vhdl/uartlite_rx.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_uartlite_v2_0/c01b5c67/hdl/src/vhdl/baudrate.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_uartlite_v2_0/c01b5c67/hdl/src/vhdl/uartlite_core.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_uartlite_v2_0/c01b5c67/hdl/src/vhdl/axi_uartlite.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_uartlite_0_0/sim/iprop_nvme_dev_ref_design_axi_uartlite_0_0.vhd" \

vlog -64 -incr -work generic_baseblocks_v2_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \

vlog -64 -incr -work axi_infrastructure_v1_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \

vlog -64 -incr -work axi_register_slice_v2_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \

vlog -64 -incr -work axi_data_fifo_v2_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \

vlog -64 -incr -work axi_crossbar_v2_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_xbar_0/sim/iprop_nvme_dev_ref_design_xbar_0.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/src/IP_BUS_BUILDER.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/src/IP_GreyCodeSync.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/src/IP_dp_ram_block.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/src/IP_BUS_BREAKER.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/IP_axi_wr_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/src/IP_FIFO_BRAM.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/src/IP_axi_lite_slave.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/IP_axi_rd_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/ipr_t10_crc_128_16.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/ipr_axi_cdma_registers.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63/iprop_axi_cdma.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_iprop_axi_cdma_0_0/sim/iprop_nvme_dev_ref_design_iprop_axi_cdma_0_0.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/IP_fifo_reg.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/IP_axi_slave_write.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/IP_axi_slave_read.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/src/IP_OneHot2Dec.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/src/IP_fast_sel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/IP_axi_slave.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/IP_fifo_wrap.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/NVMe_cmd_decode.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/NVMe_read_SQ_SM.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/NVMe_write_CQ_SM.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/src/IP_axi_master.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/NVMe_fifos.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/NVMe_sys_regs.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/NVMe_controller_regs.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_nvme_core_v1_0/3bec18d6/NVMe_core_wrap.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_iprop_nvme_core_0_0/sim/iprop_nvme_dev_ref_design_iprop_nvme_core_0_0.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_xbar_1/sim/iprop_nvme_dev_ref_design_xbar_1.v" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_proc_sys_reset_0_0/sim/iprop_nvme_dev_ref_design_proc_sys_reset_0_0.vhd" \

vcom -64 -93 -work axi_intc_v4_1  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_intc_v4_1/e741b58e/hdl/src/vhdl/double_synchronizer.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_intc_v4_1/e741b58e/hdl/src/vhdl/shared_ram_ivar.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_intc_v4_1/e741b58e/hdl/src/vhdl/pulse_synchronizer.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_intc_v4_1/e741b58e/hdl/src/vhdl/intc_core.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_intc_v4_1/e741b58e/hdl/src/vhdl/axi_intc.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_axi_intc_0_0/sim/iprop_nvme_dev_ref_design_axi_intc_0_0.vhd" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_blk_mem_gen_0_0/sim/iprop_nvme_dev_ref_design_blk_mem_gen_0_0.v" \

vcom -64 -93 -work lmb_bram_if_cntlr_v4_0  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/lmb_bram_if_funcs.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/lmb_bram_if_primitives.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/xor18.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/parity.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/parityenable.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/checkbit_handler.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/correct_one_bit.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/pselect.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/pselect_mask.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/axi_interface.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/lmb_mux.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/lmb_bram_if_cntlr_v4_0/cdd36762/hdl/vhdl/lmb_bram_if_cntlr.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_lmb_bram_if_cntlr_0_0/sim/iprop_nvme_dev_ref_design_lmb_bram_if_cntlr_0_0.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_lmb_bram_if_cntlr_1_0/sim/iprop_nvme_dev_ref_design_lmb_bram_if_cntlr_1_0.vhd" \

vcom -64 -93 -work mdm_v3_2  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/mdm_v3_2/a1222098/hdl/vhdl/mdm_primitives.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/mdm_v3_2/a1222098/hdl/vhdl/arbiter.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/mdm_v3_2/a1222098/hdl/vhdl/srl_fifo.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/mdm_v3_2/a1222098/hdl/vhdl/bus_master.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/mdm_v3_2/a1222098/hdl/vhdl/jtag_control.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/mdm_v3_2/a1222098/hdl/vhdl/mdm_core.vhd" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/mdm_v3_2/a1222098/hdl/vhdl/mdm.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_mdm_0_0/sim/iprop_nvme_dev_ref_design_mdm_0_0.vhd" \

vcom -64 -93 -work microblaze_v9_5  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/microblaze_v9_5/89e574e2/hdl/microblaze_v9_5_vh_rfs.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_microblaze_0_0/sim/iprop_nvme_dev_ref_design_microblaze_0_0.vhd" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_xbar_2/sim/iprop_nvme_dev_ref_design_xbar_2.v" \

vcom -64 -93 -work util_ds_buf_v2_01_a  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/util_ds_buf_v2_1/53fd56ac/hdl/vhdl/util_ds_buf.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_util_ds_buf_0_0/sim/iprop_nvme_dev_ref_design_util_ds_buf_0_0.vhd" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/hdl/iprop_nvme_dev_ref_design.v" \

vlog -64 -incr -work axi_protocol_converter_v2_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \

vlog -64 -incr -work axi_clock_converter_v2_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_clock_converter_v2_1/07772de4/hdl/verilog/axi_clock_converter_v2_1_axic_sync_clock_converter.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_clock_converter_v2_1/07772de4/hdl/verilog/axi_clock_converter_v2_1_axic_sample_cycle_ratio.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_clock_converter_v2_1/07772de4/hdl/verilog/axi_clock_converter_v2_1_axi_clock_converter.v" \

vlog -64 -incr -work axi_dwidth_converter_v2_1  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_a_downsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_b_downsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_r_downsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_w_downsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi_downsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_downsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_a_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer_pktfifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer_pktfifo.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi_upsizer.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_top.v" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog +incdir+${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/ipshared/intelliprop/iprop_axi_cdma_v1_0/2a350f63 \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_ds_0/sim/iprop_nvme_dev_ref_design_auto_ds_0.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_pc_0/sim/iprop_nvme_dev_ref_design_auto_pc_0.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_ds_1/sim/iprop_nvme_dev_ref_design_auto_ds_1.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_ds_2/sim/iprop_nvme_dev_ref_design_auto_ds_2.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_pc_1/sim/iprop_nvme_dev_ref_design_auto_pc_1.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_cc_0/sim/iprop_nvme_dev_ref_design_auto_cc_0.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_ds_3/sim/iprop_nvme_dev_ref_design_auto_ds_3.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_pc_2/sim/iprop_nvme_dev_ref_design_auto_pc_2.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_ds_4/sim/iprop_nvme_dev_ref_design_auto_ds_4.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_pc_3/sim/iprop_nvme_dev_ref_design_auto_pc_3.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_ds_5/sim/iprop_nvme_dev_ref_design_auto_ds_5.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_pc_4/sim/iprop_nvme_dev_ref_design_auto_pc_4.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_ds_6/sim/iprop_nvme_dev_ref_design_auto_ds_6.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_pc_5/sim/iprop_nvme_dev_ref_design_auto_pc_5.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_pc_6/sim/iprop_nvme_dev_ref_design_auto_pc_6.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_us_0/sim/iprop_nvme_dev_ref_design_auto_us_0.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/ip/iprop_nvme_dev_ref_design_auto_cc_1/sim/iprop_nvme_dev_ref_design_auto_cc_1.v" \
"${NVME_DEV}/NVMe_dev_ref_design.srcs/sources_1/bd/iprop_nvme_dev_ref_design/hdl/iprop_nvme_dev_ref_design_wrapper.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"

