######################################################################
#
# File name : root_complex_compile.do
# Created on: Tue Jun 02 16:08:30 MDT 2015
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib work
vlib msim

vlib msim/lib_pkg_v1_0
vlib msim/fifo_generator_v12_0
vlib msim/lib_fifo_v1_0
vlib msim/blk_mem_gen_v8_2
vlib msim/lib_bmg_v1_0
vlib msim/axi_pcie_v2_6
vlib msim/xil_defaultlib
vlib msim/generic_baseblocks_v2_1
vlib msim/axi_infrastructure_v1_1
vlib msim/axi_register_slice_v2_1
vlib msim/axi_data_fifo_v2_1
vlib msim/axi_crossbar_v2_1
vlib msim/lib_cdc_v1_0
vlib msim/proc_sys_reset_v5_0
vlib msim/axi_bram_ctrl_v4_0
vlib msim/axi_clock_converter_v2_1
vlib msim/axi_protocol_converter_v2_1
vlib msim/axi_dwidth_converter_v2_1

vmap lib_pkg_v1_0 msim/lib_pkg_v1_0
vmap fifo_generator_v12_0 msim/fifo_generator_v12_0
vmap lib_fifo_v1_0 msim/lib_fifo_v1_0
vmap blk_mem_gen_v8_2 msim/blk_mem_gen_v8_2
vmap lib_bmg_v1_0 msim/lib_bmg_v1_0
vmap axi_pcie_v2_6 msim/axi_pcie_v2_6
vmap xil_defaultlib msim/xil_defaultlib
vmap generic_baseblocks_v2_1 msim/generic_baseblocks_v2_1
vmap axi_infrastructure_v1_1 msim/axi_infrastructure_v1_1
vmap axi_register_slice_v2_1 msim/axi_register_slice_v2_1
vmap axi_data_fifo_v2_1 msim/axi_data_fifo_v2_1
vmap axi_crossbar_v2_1 msim/axi_crossbar_v2_1
vmap lib_cdc_v1_0 msim/lib_cdc_v1_0
vmap proc_sys_reset_v5_0 msim/proc_sys_reset_v5_0
vmap axi_bram_ctrl_v4_0 msim/axi_bram_ctrl_v4_0
vmap axi_clock_converter_v2_1 msim/axi_clock_converter_v2_1
vmap axi_protocol_converter_v2_1 msim/axi_protocol_converter_v2_1
vmap axi_dwidth_converter_v2_1 msim/axi_dwidth_converter_v2_1

vcom -64 -93 -work lib_pkg_v1_0  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/lib_pkg_v1_0/22b9c58c/hdl/src/vhdl/lib_pkg.vhd" \

vlog -64 -incr -work fifo_generator_v12_0  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/simulation/fifo_generator_vlog_beh.v" \

vcom -64 -93 -work fifo_generator_v12_0  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0_rfs.vhd" \

vlog -64 -incr -work fifo_generator_v12_0  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/fifo_generator_v12_0/15467f24/hdl/fifo_generator_v12_0_rfs.v" \

vcom -64 -93 -work lib_fifo_v1_0  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/lib_fifo_v1_0/259791c0/hdl/src/vhdl/async_fifo_fg.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/lib_fifo_v1_0/259791c0/hdl/src/vhdl/sync_fifo_fg.vhd" \

vlog -64 -incr -work blk_mem_gen_v8_2  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/blk_mem_gen_v8_2/834889ee/simulation/blk_mem_gen_v8_2.v" \

vcom -64 -93 -work lib_bmg_v1_0  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/lib_bmg_v1_0/1cb7cddc/hdl/src/vhdl/blk_mem_gen_wrapper.vhd" \

vlog -64 -incr -work axi_pcie_v2_6  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_a_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_address_decoder.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_block_bridge.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_event_handler.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_gen_sink.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_cfg_slave.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_demux.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_destraddler.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_null_gen.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_rx_pipeline.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_top.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx_arbiter.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx_pipeline.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_enhanced_tx_port_mux.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_lite_ipif.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_pcie_enhanced_core_top.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_register_slice.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axi_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_axic_register_slice.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_and.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_latch_and.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_latch_or.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_carry_or.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_command_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_comparator.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_comparator_sel.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_comparator_sel_static.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_enhanced_core_top_wrap.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_gtpa1_dual_wrapper.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_gtpa1_dual_wrapper_tile.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_rx_valid_filter_7x.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_top.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_gt_top_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_wrapper.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtx_cpllpd_ovrd.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_gt_wrapper_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_pipe_rate.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_pipe_drp.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_pipe_reset.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_7x.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_bram_7x.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_bram_top_7x.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_brams_7x.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_pipe_lane.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_pipe_misc.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_pipe_pipeline.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pcie_top.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_clock_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_drp.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_eq.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_eq_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_rate.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_rate_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_reset.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_sync.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_sync_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_user.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_user_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_wrapper.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_pipe_wrapper_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_qpll_drp_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_qpll_reset.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v1_6_qpll_wrapper_ies.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_rxeq_scan.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_pselect_f.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_r_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_slave_attachment.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/verilog/axi_pcie_v2_6_w_upsizer.v" \

vcom -64 -93 -work axi_pcie_v2_6  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_enhanced_pcie.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_pcie_mm_s_pkg.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_masterbridge_rd.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_masterbridge_wr.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_s_masterbridge_rd.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_s_masterbridge_wr.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_s_masterbridge_rd.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_s_masterbridge_wr.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_mm_s_masterbridge.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/register_block.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_read_cpl_tlp.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_read_req_tlp.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_write_req_tlp.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_slave_read.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_slave_write.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/slave_bridge.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_pcie_mm_s.vhd" \

vlog -64 -incr -work axi_pcie_v2_6  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_pipe_clock.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_qpll_wrapper.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gt_common.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_qpll_drp.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_pcie_0_0/axi_pcie_v2_6/hdl/src/verilog/axi_pcie_v2_6_pcie_7x_v2_0_2_gtp_cpllpd_ovrd.v" \

vcom -64 -93 -work axi_pcie_v2_6  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_pcie_v2_6/74d3ba04/hdl/src/vhdl/axi_pcie.vhd" \

vlog -64 -incr -work axi_pcie_v2_6  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_pcie_0_0/trigger.v" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_pcie_0_0/sim/root_complex_axi_pcie_0_0.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_blk_mem_gen_0_1/sim/root_complex_blk_mem_gen_0_1.v" \

vlog -64 -incr -work generic_baseblocks_v2_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_and.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_and.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_latch_or.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry_or.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_carry.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_command_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask_static.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_mask.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask_static.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_mask.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel_static.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_sel.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator_static.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_comparator.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux_enc.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_mux.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/generic_baseblocks_v2_1/da89d453/hdl/verilog/generic_baseblocks_v2_1_nto1_mux.v" \

vlog -64 -incr -work axi_infrastructure_v1_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axi2vector.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_axic_srl_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog/axi_infrastructure_v1_1_vector2axi.v" \

vlog -64 -incr -work axi_register_slice_v2_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axic_register_slice.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_register_slice_v2_1/03a8e0ba/hdl/verilog/axi_register_slice_v2_1_axi_register_slice.v" \

vlog -64 -incr -work axi_data_fifo_v2_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_fifo_gen.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_srl_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axic_reg_srl_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_ndeep_srl.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_data_fifo_v2_1/82d298e6/hdl/verilog/axi_data_fifo_v2_1_axi_data_fifo.v" \

vlog -64 -incr -work axi_crossbar_v2_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_arbiter_sasd.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_arbiter.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_addr_decoder.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_arbiter_resp.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_crossbar_sasd.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_crossbar.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_decerr_slave.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_si_transactor.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_splitter.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_wdata_mux.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_wdata_router.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_crossbar_v2_1/9368eebf/hdl/verilog/axi_crossbar_v2_1_axi_crossbar.v" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_xbar_1/sim/root_complex_xbar_1.v" \

vcom -64 -93 -work lib_cdc_v1_0  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/lib_cdc_v1_0/3c38df9f/hdl/src/vhdl/cdc_sync.vhd" \

vcom -64 -93 -work proc_sys_reset_v5_0  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/upcnt_n.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/sequence.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/lpf.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/proc_sys_reset_v5_0/066de7cd/hdl/src/vhdl/proc_sys_reset.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_proc_sys_reset_0_2/sim/root_complex_proc_sys_reset_0_2.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_proc_sys_reset_1_2/sim/root_complex_proc_sys_reset_1_2.vhd" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${SOURCE_HDL}/root_complex.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/xlconstant_v1_1/36911fd5/xlconstant.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_xlconstant_0_0/sim/root_complex_xlconstant_0_0.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/iprop/ip_axi_bench_v1_0/17b864dc/sources_1/imports/PCIe_axiMaster_rootComplex_ver/IP_axi_master.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/iprop/ip_axi_bench_v1_0/17b864dc/sources_1/imports/PCIe_axiMaster_rootComplex_ver/IP_axi_bench.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_IP_axi_bench_1_0/sim/root_complex_IP_axi_bench_1_0.v" \

vcom -64 -93 -work axi_bram_ctrl_v4_0  \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/srl_fifo.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/axi_bram_ctrl_funcs.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/coregen_comp_defs.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/axi_lite_if.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/checkbit_handler_64.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/checkbit_handler.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/correct_one_bit_64.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/correct_one_bit.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/xor18.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/parity.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/ecc_gen.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/lite_ecc_reg.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/axi_lite.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/sng_port_arb.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/ua_narrow.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/wrap_brst.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/rd_chnl.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/wr_chnl.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/full_axi.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/axi_bram_ctrl_top.vhd" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_bram_ctrl_v4_0/3dec2f5b/hdl/vhdl/axi_bram_ctrl.vhd" \

vcom -64 -93 -work xil_defaultlib  \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_axi_bram_ctrl_0_1/sim/root_complex_axi_bram_ctrl_0_1.vhd" \

vlog -64 -incr -work axi_clock_converter_v2_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_clock_converter_v2_1/07772de4/hdl/verilog/axi_clock_converter_v2_1_axic_sync_clock_converter.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_clock_converter_v2_1/07772de4/hdl/verilog/axi_clock_converter_v2_1_axic_sample_cycle_ratio.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_clock_converter_v2_1/07772de4/hdl/verilog/axi_clock_converter_v2_1_axi_clock_converter.v" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_auto_cc_0/sim/root_complex_auto_cc_0.v" \

vlog -64 -incr -work axi_protocol_converter_v2_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_a_axi3_conv.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi3_conv.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axilite_conv.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_r_axi3_conv.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_w_axi3_conv.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b_downsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_decerr_slave.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_simple_fifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wrap_cmd.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_incr_cmd.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_wr_cmd_fsm.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_rd_cmd_fsm.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_cmd_translator.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_b_channel.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_r_channel.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_aw_channel.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s_ar_channel.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_b2s.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_protocol_converter_v2_1/017861a2/hdl/verilog/axi_protocol_converter_v2_1_axi_protocol_converter.v" \

vlog -64 -incr -work axi_dwidth_converter_v2_1  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_a_downsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_b_downsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_r_downsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_w_downsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi_downsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_downsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi4lite_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_a_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_w_upsizer_pktfifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_r_upsizer_pktfifo.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_axi_upsizer.v" \
"${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_dwidth_converter_v2_1/d98fa611/hdl/verilog/axi_dwidth_converter_v2_1_top.v" \

vlog -64 -incr -work xil_defaultlib  +incdir+${NVME_RC}/root_complex.srcs/sources_1/ipshared/xilinx.com/axi_infrastructure_v1_1/cf21a66f/hdl/verilog \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_auto_ds_0/sim/root_complex_auto_ds_0.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_auto_pc_0/sim/root_complex_auto_pc_0.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_auto_ds_1/sim/root_complex_auto_ds_1.v" \
"${NVME_RC}/root_complex.srcs/sources_1/bd/root_complex/ip/root_complex_auto_us_0/sim/root_complex_auto_us_0.v" \

# compile glbl module
vlog -work xil_defaultlib "glbl.v"
vlog -work work glbl.v
